### ISSUE TITLE
Some help generalizing your TSP demo

### ISSUE THREAD

**Issue by simonp0420** [ac-tuwien/MHLib.jl#3]
Please see my question at https://discourse.julialang.org/t/need-a-combinatorial-optimizer-for-black-box-function/68791.  I think your package might be what I need, but I have looked at your TSP test and I would need some guidance/pointers on how to generalize this for an arbitrary objective function.  Would you be able to outline what is needed to do this?

Thanks in advance,
Peter

**Comment by graidl** [comment]
Dear Simon, yes, in principle `MHLib` and the TSP demo can be a good and comparably easy starting point for your work.
What you just would have to do to get a first version running, starting from `TSP.jl`:
- Modify `TSPInstance`` and the respective methods to represent your problem intance, i.e., load and store all relevant data.
- Possibly modify `to_maximize` if you have a maximization problem.
- Adapt `calc_objective` to indeed determine the objective value for the given solution (permutation) for your problem. 
- `MHLib.PermutationSolutions.two_opt_move_delta_eval` may be simply removed for a first try. It realizes a more efficient incremental update of a solution's objective value for the classical 2-opt move. Depending on your problem, however, it may be difficult to realize. If you can't, simply don't use it. However, if you are able to do a more efficient incremental update like in case of the TSP, this may substantially speed up the optimization.

In essence, that's it! Look into the exampls in `runtests_tsp.jl` and `runtests.jl` how to run an actiual variable neighborhood search or large neighborhood search. Clearly, it is important to tune the optimization with the parameters, e.g., the number and size of shaking methods, as well as the termination condition.

Note that this realizes a simpleGVNS (or LNS) based on the 2-opt move. To make the optimization more effective, it is always a good idea to think more about the problem's specific properties and structe, and possibly develop dedicated own neighborhood operators. For example, maybe the `random_two_exchange_move`, which is also realized in `PermutationSolutions.jl` is more appropriate in your case.

Good luck with with your project, and I am happy to help when further questions arise conferning `MHLib`!

**Comment by simonp0420** [comment]
Thanks for your kind reply, both here and in the Discourse forum.  I'll attempt to follow your guidance.
