### ISSUE TITLE
Need some help with a Variable Neighborhood Search Implementation 

### ISSUE THREAD

**Issue by ghost** [ac-tuwien/MHLib.jl#4]
Hello there! My team is trying to use this library to implement a general variable neighborhood search (VNS), but we are unsure how. We want to use the classic Rastrigin function `f(x) = 10length(x) + sum( x.^2 - 10cos.(2π*x))` to benchmark this algorithm. Ultimately, we want to map out the progression of the algorithm via a scatterplot such as the one we created for the Whale Optimization Algorithm [here](https://gifyu.com/image/SxWNn). 

Our source code for the WOA graph is [here](https://pastebin.com/Yn9Vef0d). We are looking to do something similar with the Variable Search Algorithm. 

We would greatly appreciate it if you would please give us some steps in the right direction to achieve the goals previously outlined! We are beginners in Julia, so we apologize if our code doesn't follow best practices. 

![WOA_Animation](https://user-images.githubusercontent.com/13796805/170557616-1033099f-ca16-443d-9da6-47084335c91c.gif)

**Comment by graidl** [comment]
First of all, I'm happy that you consider MHLib interesting for your work!

Note that MHLib is not an optimization package which you can simply call for some function you want to optimize. It is more a problem-independent framework containing many utilities to realize a VNS, among other metaheuristics, relatively easily.

For the VNS, what you need to define are at least a solution type for your problem and some neighborhood functions. In terms of the classical General Variable Neighborhood Search, we distinguish between local improvement neighborhoods and shaking functions. Plus you can also specify some function(s) for creating initial solutions. I recommend to just have a look at the various examples implemented in the test directory to get an idea of how to use MHLib. Just use one of them as a template for your work.

You say that you want to optimize the Rastrigin function, which, however, is a continuous parameter optimization problem. Note that approaches like VNS are more commonly used for discrete/combinatorial optimization problems, which we also had more in mind when developing MHLib. I don't know what neighborhood structures you envision for your VNS, but maybe other optimization approaches dedicated for continuous parameter optimization are better suited than a VNS.
