### ISSUE TITLE
In GVNSs module vnd! is called before use_vnd flag is set

### ISSUE THREAD

**Issue by jamesmulhern** [ac-tuwien/MHLib.jl#5]
In the GVNS function there is a flag called `use_vnd` that will eliminate the vnd call from the GVNS loop.   This should allow for utilization of the GVNS function as a local search.  

The issue is that `vnd!` is called on line 91 as part of the if statement. This results in an infinite loop when `gvns.meths_li = MHMethod[]`.

**Comment by graidl** [comment]
Thanks for pointing out this issue! It is fixed in the new version.
